### PR TITLE
add x509_read_timestamp

### PR DESCRIPTION
**Pull request by jfcoz**
For monitoring tools that does not have timestamp calculation functions

### CODE REVIEW

**Comment by npdgm** [comment]
Hey @jfcoz,
Thanks for your contribution, that's a good workaround for Datadog.
I made the metric optional, so you can have it adding argument `--timestamp-metric`. We want to keep storage efficient for Prometheus and other TSDB that would not need the timestamp for alerting but still be asked to store a constantly changing value otherwise.
It won't be released now as I want @arcln to have a look before and they're not available today.
Our Helm Chart will then be updated right after with a flag to enable `x509_read_timestamp`.
Cheers

**Review by npdgm — APPROVED** [review]
LGTM

**Comment by jfcoz** [comment]
@npdgm , thanks, very good idea to make it optional.

**Comment by jfcoz** [comment]
Maybe it would be simple with a `--calculate-delays` argument which would add :
- `x509_cert_valid_since_seconds`
- `x509_cert_expire_in_seconds`

What do you think ?

**Comment by npdgm** [comment]
@jfcoz thanks for the latest patch. Sorry I didn't keep you up-to-date this morning, I think @arcln implemented it too and is probably testing it. We agreed on your suggestion for new metric names and the idea of exposing relative metrics instead of a timestamp.

**Review by arcln — APPROVED** [review]

**Comment by jfcoz** [comment]
Thank you both ! I’ve test a build from the last commit and it works perfectly.

**Comment by arcln** [comment]
Great to hear it's working on your end. Just to resume :

The flag to enable this feature is called `--expose-relative-metrics`.
The added metrics are `x509_cert_expires_in_seconds` and `x509_cert_valid_since_seconds`.

**Comment by npdgm** [comment]
Available in Helm Chart version 1.10.0
You may add to values: `exposeRelativeMetrics: true`

**Pull request merged**
