### PR TITLE
Use prometheus/exporter-toolkit

### PR DESCRIPTION
**Pull request by v0ctor**
Prometheus has a library (_[exporter-toolkit](https://github.com/prometheus/exporter-toolkit)_) that easily allows exporters to reuse the same HTTP server implementation, which may be configured homogeneously among all the exporters.

It adds support for the following features:
- TLS
- TLS client authentication
- HTTP basic auth

The library is used by the official node exporter, among others.

This PR adapts the project to use _exporter-toolkit_, keeping backwards compatibility.

### Considerations

Prometheus uses _[go-kit/log](https://github.com/go-kit/log)_, and it offers support for Logrus.
```go
// kit "github.com/go-kit/kit/log/logrus"
// log "github.com/sirupsen/logrus"

logger := kit.NewLogger(log.StandardLogger())
```

However, output is weird:
```
INFO[0000]                                               address="127.0.0.1:9793" fields.level=info fields.msg="Listening on"
INFO[0000]                                               address="127.0.0.1:9793" fields.level=info fields.msg="TLS is disabled." http2=false
```

For that reason, I have decided to create a _go-kit_ logger and pass it to the library. Output is more convenient:
```
level=info ts=2022-11-17T12:24:31.715Z caller=tls_config.go:232 msg="Listening on" address=127.0.0.1:9793
level=info ts=2022-11-17T12:24:31.715Z caller=tls_config.go:235 msg="TLS is disabled." http2=false address=127.0.0.1:9793
```

It might be a good idea to replace Logrus by _go-kit/log_ to avoid this problem. Not for any special reason, because Logrus is an excellent library, but for consistency when taking advantage of other libraries in the Prometheus scope.

I can take care of making this change in another PR, but I wanted to discuss it first and make sure that these changes are going to be integrated.

### CODE REVIEW

**Comment by v0ctor** [comment]
I'm trying to reproduce the test failure locally. 🕵️‍♂️

**Comment by npdgm** [comment]
Hi @v0ctor
Looks really neat, thanks for this contribution :+1:
We may want to add a few knobs to the Helm Chart too, I can handle that later on releasing.

> I'm trying to reproduce the test failure locally. male_detective
Awesome, thanks a lot :smile: 

Will wait for @arcln to have a look too, as I didn't work on tests at all.

Cheers

**Comment by npdgm** [comment]
Huh. I'm figuring out why test did not run again...

**Comment by v0ctor** [comment]
Thank you, @npdgm!

Let me update the Helm chart to make this PR consistent.

By the way, I've just seen the tests running, but they just disappeared.

**Comment by v0ctor** [comment]
I've just checked the Helm chart and I realized that updating it may be more difficult than I expected. 😅 For example, X.509 certificates for TLS should be mounted from a secret, and it must be well-thought-out first.

As you've stated, maybe it's better to do it later.

**Comment by v0ctor** [comment]
Have you had a chance to take a look at this?

Thanks in advance!

**Comment by npdgm** [comment]
> Have you had a chance to take a look at this?
Working on the Chart now, let's have it released ASAP :)

**Comment by npdgm** [comment]
Indeed we lack a few knobs on this chart to fully take advantage of exporter-toolkit.

Obviously I'm adding Helm values for the Web Configuration to be passed by string or referencing an existing Secret. And for the later we already have `extraDeploy:` to include such object in the release (Secret, SealedSecret, etc.).
Going as far as making a template for this configuration doesn't seem like a great idea at that stage, especially given [the warning on it's experimental status](https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md).
It's good enough for managing Basic authentication.

Then we might want users to enable `tls_server_config` , which require a facility to project into the container other Secrets containing certificates and keys. Again I don't feel like implementing much exporter-toolkit specifics in values. But it's a great opportunity to introduce `extraVolumes` and `extraVolumeMounts` mechanics.

That's a lot of changed templates and much testing is required.

**Comment by v0ctor** [comment]
I really appreciate your work, @npdgm! :)

**Comment by npdgm** [comment]
> I really appreciate your work, @npdgm! :)

Thanks for the kind words :smile: Have a great day

**Pull request merged**
